@host=https://localhost:5001

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstname": "Victor",
    "lastname": "Canto",
    "email": "iamvictorcanto2@gmail.com",
    "password": "Victor123"
}
